openapi: 3.0.0
info:
  title: Microservice API
  version: unknown
  description: This is an OAS description of this Microservice REST API
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/about:
    get:
      tags:
        - Documentation
      summary: Retrieve the entire README file as HTML.
      description: Reads the entire README file and returns its content as HTML.
      responses:
        '200':
          description: Successfully retrieved the README file content as HTML.
          content:
            text/html:
              schema:
                type: string
                description: The HTML content of the README file.
        '500':
          description: Error reading the README file.
          content:
            text/plain:
              schema:
                type: string
                description: Error message when the file cannot be read.
                example: 'Error reading the file: [error details]'
  /api/v1/version:
    get:
      tags:
        - Documentation
      summary: Retrieve the API version from the .version file.
      description: >-
        Reads the .version file and returns its content as part of a JSON
        message.
      responses:
        '200':
          description: Successfully retrieved the API version.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The current API version.
                    example: v1.0.0
        '500':
          description: Error reading the .version file.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message summary.
                    example: There was an error retrieving API version
                  error:
                    type: string
                    description: Detailed error message.
                    example: 'ENOENT: no such file or directory, open ''.version'''
  /api/v1/changelog:
    get:
      tags:
        - Documentation
      summary: Retrieve the API changelog.
      description: >
        Reads the `CHANGELOG.md` file, parses its content, and returns it as
        HTML. Supports filtering by specific versions, multiple versions, or a
        version range.
      parameters:
        - in: query
          name: versions
          schema:
            type: string
          description: >
            Comma-separated list of release versions to retrieve (e.g.
            `v2.1.4,v2.1.2`).
        - in: query
          name: from
          schema:
            type: string
          description: >
            Starting release version for the changelog range (inclusive, e.g.
            `v2.1.2`).
        - in: query
          name: to
          schema:
            type: string
          description: >
            Ending release version for the changelog range (inclusive, e.g.
            `v2.1.4`).
      responses:
        '200':
          description: Successfully retrieved the changelog.
          content:
            text/html:
              schema:
                type: string
                description: The HTML representation of the changelog or filtered releases.
        '500':
          description: Error reading the CHANGELOG.md file.
          content:
            text/plain:
              schema:
                type: string
                description: Error message when the changelog cannot be read.
                example: >-
                  There was an error retrieving API release notes: ENOENT: no
                  such file or directory, open 'CHANGELOG.md'
  /api/v1/auth/register:
    post:
      summary: Registra un nuevo usuario como beatmaker
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  description: Nombre de usuario (úninico, mínimo 3 caracteres)
                  example: john_doe
                email:
                  type: string
                  format: email
                  description: Email del usuario (úninico)
                  example: john@example.com
                password:
                  type: string
                  minLength: 6
                  description: Contraseña (mínimo 6 caracteres)
                  example: mySecurePassword123
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - MISSING_FIELDS
                      - INVALID_DATA_TYPE
                      - INVALID_USERNAME
                      - INVALID_PASSWORD
                      - INVALID_EMAIL
                    example: INVALID_EMAIL
                  message:
                    type: string
                    example: Email format is invalid
                  details:
                    type: object
                    description: Detalles específicos del error (solo para MISSING_FIELDS)
        '409':
          description: Usuario o email ya existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - USERNAME_EXISTS
                      - EMAIL_EXISTS
                    example: USERNAME_EXISTS
                  message:
                    type: string
                    example: Username already exists
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: REGISTRATION_FAILED
                  message:
                    type: string
                    example: Registration failed
  /api/v1/auth/login:
    post:
      summary: Inicia sesión y obtiene tokens de acceso
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - identifier
                - password
              properties:
                identifier:
                  type: string
                  description: Username o email del usuario
                  example: john_doe
                password:
                  type: string
                  description: Contraseña del usuario
                  example: mySecurePassword123
      responses:
        '200':
          description: Login exitoso con tokens
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  accessToken:
                    type: string
                    description: Token de acceso (JWT, expira en 15 minutos)
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  refreshToken:
                    type: string
                    description: Token de actualización (expira en 7 días)
                    example: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - MISSING_FIELDS
                      - INVALID_DATA_TYPE
                      - EMPTY_FIELDS
                    example: MISSING_FIELDS
                  message:
                    type: string
                    example: Identifier and password are required
                  details:
                    type: object
                    description: Detalles específicos del error
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: INVALID_CREDENTIALS
                  message:
                    type: string
                    example: Invalid credentials
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: LOGIN_FAILED
                  message:
                    type: string
                    example: Login failed
  /api/v1/auth/refresh:
    post:
      summary: Refresca el access token usando un refresh token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Nuevo access token generado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                  accessToken:
                    type: string
                    description: Nuevo access token
                  refreshToken:
                    type: string
                    description: Nuevo refresh token (rotado)
        '401':
          description: Refresh token inválido o expirado
  /api/v1/auth/logout:
    post:
      summary: Cierra sesión revocando tokens (refresh y opcionalmente access)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: Refresh token a revocar (requerido)
                  example: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
                accessToken:
                  type: string
                  description: Access token a revocar (opcional, recomendado)
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Logout exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successful
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - MISSING_REFRESH_TOKEN
                      - INVALID_DATA_TYPE
                    example: MISSING_REFRESH_TOKEN
                  message:
                    type: string
                    example: Refresh token is required
        '404':
          description: Token no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: TOKEN_NOT_FOUND
                  message:
                    type: string
                    example: Refresh token not found
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: LOGOUT_FAILED
                  message:
                    type: string
                    example: Logout failed
  /api/v1/auth/revoke-all:
    post:
      summary: Revoca todos los tokens de un usuario (requiere autenticación)
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Todos los tokens revocados
        '401':
          description: No autenticado
  /api/v1/health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns basic information to verify that the API is running properly.
      responses:
        '200':
          description: API is healthy and responding.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  message:
                    type: string
                    example: Health check successful
                  version:
                    type: string
                    example: 1.0.0
                  uptime:
                    type: number
                    example: 123.45
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-11-08T13:41:47.074Z'
                  environment:
                    type: string
                    example: development
                  db:
                    type: string
                    example: connected
tags: []
